In [2]:
import pandas as pd
import numpy as np

In [11]:
orders = pd.DataFrame({
    'order_id':[1,2,3,4,5],
    'store':['강남','잠실','강남','홍대','강남'],
    'amount':[10000, 20000, 15000, 30000, 25000]
})

In [6]:
store_count = orders['store'].value_counts()
store_count

store
강남    3
잠실    1
홍대    1
Name: count, dtype: int64

In [13]:
# 매장별 주문 건수화 총금액 함께 집계
orders.groupby('store').agg(order_count=('order_id','count'), total_amount=('amount','sum')).reset_index()

  store  order_count  total_amount
0    강남            3         50000
1    잠실            1         20000
2    홍대            1         30000

In [14]:
# 고객 데이터
customers = pd.DataFrame({
    'customer_id':[101,102,103],
    'customer_name':['앨리스','밥','캐롤']
})

In [16]:
orders = pd.DataFrame({
    'order_id':[1,2,3,4,5],
    'store':['강남','잠실','강남','홍대','강남'],
    'amount':[10000, 20000, 15000, 30000, 25000],
    'customer_id':[101,102,104,np.nan,np.nan]
})
orders

   order_id store  amount  customer_id
0         1    강남   10000        101.0
1         2    잠실   20000        102.0
2         3    강남   15000        104.0
3         4    홍대   30000          NaN
4         5    강남   25000          NaN

In [17]:
# merge
inner_join = pd.merge(orders, customers, on='customer_id', how='inner')
inner_join

   order_id store  amount  customer_id customer_name
0         1    강남   10000        101.0           앨리스
1         2    잠실   20000        102.0             밥

In [18]:
left_join = orders.merge(customers, on='customer_id', how='left')
left_join

   order_id store  amount  customer_id customer_name
0         1    강남   10000        101.0           앨리스
1         2    잠실   20000        102.0             밥
2         3    강남   15000        104.0           NaN
3         4    홍대   30000          NaN           NaN
4         5    강남   25000          NaN           NaN

In [34]:
df = pd.read_csv('Titanic-Dataset.csv')
df.shape

(891, 12)

In [35]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [37]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [38]:
missing_count = df.isnull().sum()
missing_count[['Age','Cabin','Embarked']]
missing_value = df.isnull().sum()/len(df)
missing_value[['Age','Cabin','Embarked']].round(3)*100

Age         19.9
Cabin       77.1
Embarked     0.2
dtype: float64

In [39]:
df['Age'] =df['Age'].fillna(df['Age'].median())

In [40]:
df['Sex'] = df['Sex'].map(lambda x: 1 if x =='female' else 0)
df['Sex'].value_counts()

Sex
0    577
1    314
Name: count, dtype: int64

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    int64
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(6), str(4)
memory usage: 83.7 KB

In [43]:
df_cabin = df['Cabin'].str[0]
df_cabin.value_counts()

Cabin
C    59
B    47
D    33
E    32
A    15
F    13
G     4
T     1
Name: count, dtype: int64